### ISSUE TITLE
Broken link inside "Tutorial"

### ISSUE THREAD

**Issue by andregri** [reactjs/it.react.dev#336]
At this line of the file [tutorial.md](https://github.com/reactjs/it.reactjs.org/blob/d80bfbf7d5f7fa91eb093a782f9ada217872b0f8/content/tutorial/tutorial.md?plain=1#L48), the link to the Italian version of the Javascript Guide is broken because Mozilla deleted the Italian translation.

**Comment by deblasis** [comment]
Not applicable anymore, we have a new website now
