### ISSUE TITLE
Translation of "Effect"

### ISSUE THREAD

**Issue by mattveraldi** [reactjs/it.react.dev#488]
How should we translate "Effect" in the context of `useEffect`? I am specifically translating the page "You Might Not Need An Effect".

I would use "Effetto" because that's what it basically is, not only the terminology but also the mental model.
On the other hand, leaving the English term "Effect" might help new readers understand better that we are specifically talking about the "useEffect".

- "Potresti non avere bisogno di un Effetto" - new reader may not understand that "Effetto" is related to "useEffect" from the title alone.
- "Potresti non aver bisogno di useEffect" - it might be more clear for new readers.

I like "Effetto" more, because it is generic enough to give new readers the right mental model to use when thinking about side effects handling. "useEffect" is the hook so it may be a stretch, "Effect" is just the English word and it may seem a wrong translation. what do you think?

**Comment by mattia-sanfilippo** [comment]
Hey @mattveraldi 👋

Thanks for thinking about it. I would be more inclined to use "Effetto" too. I also checked the [Spanish version of the documentation](https://es.react.dev/learn/you-might-not-need-an-effect), and they use the same term/meaning (_efecto_) as well.

We can also update the [Glossary](https://github.com/reactjs/it.react.dev/blob/main/GLOSSARY.md) by adding this term to the common translations.

**Comment by mattveraldi** [comment]
Great, then I will translate "Effect" as "Effetto" always in title-case so that users will *know* that it has a technical meaning other than a literal one. Thanks.
